検索機能の実装
hak-chami/chobi_memo pull request #22
Opened 2018-07-27 12:22 UTC by hak-chami

# WHAT
検索機能を実装

- 検索機能
- フォームデザイン調整

![chobimemo025-1](https://user-images.githubusercontent.com/38174128/43320344-25521ca8-91e3-11e8-907b-0df5d0ba3c12.png)

2018-07-27 18:06 UTC, ArakawaShintaro requested changes

2018-07-27 18:06 UTC, ArakawaShintaro commented on app/controllers/words_controller.rb
> +    @words = search(params[:search])
このメソッド化のやり方はちょっと微妙ですね
ロジックはモデルに書きたいです。
どのモデルに書くかは考えてみてください！

2018-07-27 18:06 UTC, ArakawaShintaro commented on app/controllers/words_controller.rb
> +  def search(search)
メソッドのインターフェースもあまりよくないです。
メソッド名と引数名がかぶってるのが違和感あります。

2018-07-27 18:06 UTC, ArakawaShintaro commented on app/views/words/index.html.erb
> +    <%= form_tag words_path, :method => 'get' do %>
> :method => 'get'

これいらない気がしますが、どうでしょう。

2018-07-28 01:40 UTC, hak-chami commented on app/controllers/words_controller.rb
> +    @words = search(params[:search])
最初はモデルに書いていたんですが、ヘルパーメソッド（current_user）が使えなくなるのでコントローラーに書きました。
やはりモデルに書いた方が良いのでしょうか？

2018-07-28 02:04 UTC, hak-chami commented on app/views/words/index.html.erb
> +    <%= form_tag words_path, :method => 'get' do %>
ないとcreateに飛んでしまうのでこのままとします。

2018-07-28 05:40 UTC, ArakawaShintaro commented on app/controllers/words_controller.rb
> +    @words = search(params[:search])
current_userを引数で渡してあげれば、そのuserはわかりますよね。
モデルに書くべきです。

2018-07-28 05:40 UTC, ArakawaShintaro commented on app/views/words/index.html.erb
> +    <%= form_tag words_path, :method => 'get' do %>
おっと、すみませんmm
form_tagはrails5系からはform_withに変わってるので変更しておきましょう

2018-07-28 05:44 UTC, hak-chami commented on app/controllers/words_controller.rb
> +    @words = search(params[:search])
承知しました。やってみます。

2018-07-28 05:44 UTC, hak-chami commented on app/views/words/index.html.erb
> +    <%= form_tag words_path, :method => 'get' do %>
承知しました。

2018-07-28 08:11 UTC, ArakawaShintaro approved these changes
LGTM

2018-07-28 08:11 UTC, ArakawaShintaro commented on app/models/word.rb
> +  def self.search(current_user, search_word)
細かいですが、こちらの引数では汎用的な名前のuserでもいいのかなぁと思いますが、
いったんこれで大丈夫です！

2018-07-28 09:27 UTC, merged